jest.mock("./settings", () => ({ requirePro: jest.fn() }));
jest.mock("../utils/log", () => ({
  actionLog: { info: jest.fn(), error: jest.fn() },
}));
jest.mock("./email", () => ({ sendEmail: jest.fn() }));
jest.mock("./messages", () => ({
  getAllUnsubscribeMethodsForVendor: jest.fn(),
  markListUnsubscribed: jest.fn(),
}));

import {
  getAllUnsubscribeMethodsForVendor,
  markListUnsubscribed,
} from "./messages";
import { sendEmail } from "./email";
import { unsubscribeVendor } from "./unsubscribe";

const getMethods = jest.mocked(getAllUnsubscribeMethodsForVendor);
const markList = jest.mocked(markListUnsubscribed);
const send = jest.mocked(sendEmail);

beforeEach(() => {
  jest.clearAllMocks();
});

describe("unsubscribeVendor", () => {
  it("posts an RFC 8058 request before marking that list unsubscribed", async () => {
    const url = "https://example.test/unsubscribe/token";
    getMethods
      .mockReturnValueOnce([{ method: "rfc8058", url }])
      .mockReturnValueOnce([]);
    const request = jest.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 204,
    } as Response);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "unsubscribed",
      method: "one_click",
      url,
      remainingTargets: 0,
    });
    expect(request).toHaveBeenCalledWith(url, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: "List-Unsubscribe=One-Click",
    });
    expect(markList).toHaveBeenCalledWith(42, url);
    request.mockRestore();
  });

  it("leaves other list targets pending after completing one one-click URL", async () => {
    const listA = "https://params.example.test/unsubscribe?list=A&token=abc";
    const listB = "https://params.example.test/unsubscribe?list=B&token=abc";
    getMethods
      .mockReturnValueOnce([
        { method: "rfc8058", url: listA },
        { method: "rfc8058", url: listB },
      ])
      .mockReturnValueOnce([{ method: "rfc8058", url: listB }]);
    const request = jest.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 204,
    } as Response);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "unsubscribed",
      method: "one_click",
      url: listA,
      remainingTargets: 1,
    });
    expect(request).toHaveBeenCalledWith(listA, expect.any(Object));
    expect(markList).toHaveBeenCalledWith(42, listA);
    expect(markList).not.toHaveBeenCalledWith(42, listB);
    request.mockRestore();
  });

  it("does not update Paperweight when a one-click request fails", async () => {
    getMethods.mockReturnValue([{
      method: "rfc8058",
      url: "https://example.test/unsubscribe/token",
    }]);
    const request = jest.spyOn(global, "fetch").mockResolvedValue({
      ok: false,
      status: 500,
    } as Response);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "failed",
      method: "one_click",
      error: "Server returned HTTP 500",
    });
    expect(markList).not.toHaveBeenCalled();
    request.mockRestore();
  });

  it("sends a mailto request before marking that list unsubscribed", async () => {
    const url = "mailto:leave+token@example.test?subject=Remove%20me";
    getMethods
      .mockReturnValueOnce([{ method: "list-unsubscribe", url }])
      .mockReturnValueOnce([]);
    send.mockResolvedValue({ success: true });

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "unsubscribed",
      method: "email",
      url,
      remainingTargets: 0,
    });
    expect(send).toHaveBeenCalledWith(
      "leave+token@example.test",
      "Remove me",
      "This message was automatically generated by paperweight.email",
    );
    expect(markList).toHaveBeenCalledWith(42, url);
  });

  it("requires manual action for a browser unsubscribe method and leaves it pending", async () => {
    const url = "https://example.test/preferences/token";
    getMethods.mockReturnValue([{
      method: "footer",
      url,
    }]);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "manual_required",
      method: "browser",
      url,
      remainingTargets: 1,
    });
    expect(send).not.toHaveBeenCalled();
    expect(markList).not.toHaveBeenCalled();
  });

  it("strips wrapping angle brackets from a browser unsubscribe URL", async () => {
    getMethods.mockReturnValue([{
      method: "list-unsubscribe",
      url: "<https://example.test/preferences/token>",
    }]);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "manual_required",
      method: "browser",
      url: "https://example.test/preferences/token",
      remainingTargets: 1,
    });
    expect(markList).not.toHaveBeenCalled();
  });

  it.each([
    "file:///etc/passwd",
    "javascript:alert(1)",
    "ftp://example.test/unsub",
    "not a url",
    "https://",
    "",
  ])("does not return a non-http unsubscribe URL (%s)", async (url) => {
    getMethods.mockReturnValue([{
      method: "footer",
      url,
    }]);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "not_available",
      remainingTargets: 1,
    });
    expect(send).not.toHaveBeenCalled();
    expect(markList).not.toHaveBeenCalled();
  });

  it("does nothing when no unsubscribe method is available", async () => {
    getMethods.mockReturnValue([]);

    await expect(unsubscribeVendor(42)).resolves.toEqual({
      status: "not_available",
      remainingTargets: 0,
    });
    expect(send).not.toHaveBeenCalled();
    expect(markList).not.toHaveBeenCalled();
  });
});


it("blocks Free unsubscribe before any request or local status change", async () => {
  const { requirePro } = await import("./settings");
  jest.mocked(requirePro).mockImplementationOnce(() => { throw new Error("Pro required"); });
  const request = jest.spyOn(global, "fetch");
  await expect(unsubscribeVendor(42)).rejects.toThrow("Pro required");
  expect(request).not.toHaveBeenCalled();
  expect(send).not.toHaveBeenCalled();
  expect(markList).not.toHaveBeenCalled();
  request.mockRestore();
});
